[package]
name = "warp-websockets-example"
version = "0.1.0"
authors = ["stefan.baumgartner <Stefan.Baumgartner@dynatrace.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
tokio = { version = "1", features = ["full"] }
warp = "0.3.1"
tokio-stream = "0.1.6"
futures = "0.3.15"
